### ISSUE TITLE
这个是需要数据库？

### ISSUE THREAD

**Issue by iphyer** [jinfagang/tensorflow_poems#6]
```
tensorflow.python.framework.errors_impl.NotFoundError: /Volumes/Disk2/CodeSpace/AISpace/tfspace/chatbot_repos/tang_poetry/checkpoints/poems

```

**Comment by jinfagang** [comment]
No, I wrongly hard coded some path, you can change it in tf.flags settings, sorry about that.

**Comment by zzuyelei** [comment]
I just came across the same problem iphyer have, and I solve it by simply delete the checkpoint file in the path ./checkpoints/poems/. I post here just because it may be helpful  for someone who have the same problem

**Comment by jinfagang** [comment]
The real problem is checkpoints dir has an checkpoint file, you can delete it, I already updated repo.

**Comment by iphyer** [comment]
OK, then I guess this issue can be closed.

And I have check the result, everything looks fine now.

![photo](http://ge.tt/2eI3HOj2)

So, if used in only CPU case, how long can the training be finished?

**Comment by jinfagang** [comment]
it depends, just pick a cup of caffe relax and wait our poem master generate poems

**Comment by zzuyelei** [comment]
The training process is extremely slow, maybe simply because of my slow CPU or no GPU or running in vm?
After hours,I lost my patience and Ctrl+C to ternimate it. I extremely hurry for the result. And run with --no-train. That's even more frustrated, after more than an hour nothing happened, it just hanging there and no result returned. I just wonder whether only when the training is ternimate itself and cant manually interrupted or is there I missed something?

**Comment by jinfagang** [comment]
Basicly, train 6-10 epochs can generate fair poem already, no need to train a lot of iterations.

**Comment by iphyer** [comment]
Yeah, For me it takes 4 i5 CPU 1.5 days.

**Comment by iphyer** [comment]
不过我还是没理解怎么产生藏头诗

**Comment by iphyer** [comment]
比如，我可以实现单个字古诗的生成，如下图，

![1](https://cloud.githubusercontent.com/assets/1913891/24319549/2bef391a-10ed-11e7-980b-6f438063dcaf.png)

但是如果是藏头诗就会报错。

![2](https://cloud.githubusercontent.com/assets/1913891/24319552/31c9d20a-10ed-11e7-917e-42072a3d7394.png)

这个是我使用方法不对？

**Comment by jinfagang** [comment]
Currently only support first single word compose poems. May be future add more features.

**Comment by iphyer** [comment]
OK. that's cool.
